### PR TITLE
Operations

### PR DESCRIPTION
**Pull request by bartekn**
This PR adds a friendly API to create the following operations:
- Manage Offer
- Create Passive Offer
- Set Options
- Account Merge
- Inflation

Examples can be found in [test examples](https://github.com/stellar/go-stellar-base/pull/31/files#diff-b0bd7cdedee15ec71276b9561bda7cbc).
Close https://github.com/stellar/go-stellar-base/issues/28.

### CODE REVIEW

**Comment by nullstyle** [comment]
So, I'm still concerned with how you're using prices:

- The build package shouldn't contain the code for approximating the ration price from a string.  Instead, introduce a `price` package, similar to the already existing `amount` package and add a `price.Parse()` func.

-  I don't think we need the external decimal library.  Can you explain to me why the path I took for amounts in `amount.Parse` won't work for prices?

**Comment by bartekn** [comment]
Good point about `price` package, I will move it there.
When it comes to `math/big` package, the only equivalent of `floor` function I could find in `big.Rat` is [`Rat.FloatString`](https://golang.org/pkg/math/big/#Rat.FloatString) (and then [`Rat.SetString`](https://golang.org/pkg/math/big/#Rat.SetString) to create `big.Rat` object again) and I think it looks a bit clunky. `decimal` does not require creating any intermediate objects.
The other thing is how method chaining works:
```go
	// big.Rat
	six := &big.Rat{}
	six.Mul(one, two).Add(six, four)
	// six == 6 and one == 1 but it looks terrible
	newSix := one.Mul(one, two).Add(one, four))
	// newSix == 6 but one == 6 too
	
	// decimal
	six := one.Mul(two).Add(four)
	// one is still equal 1 and six == 6
```
`decimal` way of chaining is in my opinion easier to read.

**Comment by nullstyle** [comment]
>  When it comes to math/big package, the only equivalent of floor function I could find in big.Rat

Conceptually, the floor of a fraction is jus:
m = num * dem
flooredm = (m - (num % dem))
newn - flooredm / demo

**Comment by nullstyle** [comment]
> I think it looks a bit clunky. decimal does not require creating any intermediate objects.

From what I understand, the big math packages in go were designed for efficiency, not ease of use.  IMO, using a clunky but well maintained stdlib package is a lesser sin than adding a new external dependency, doubly-so by introducing a second way of performing math on financial values.

It's true that it is easier to read, but I think we can offset that with good testing.

I'll tolerate the merge, but I don't think it should be added.

**Comment by bartekn** [comment]
OK, I switched to `math/big`. Let me know if you see any other issues.

**Comment by nullstyle** [comment]
+1

**Pull request merged**
